"""
Configuration file for allowed symbols.
Contains list of symbols that are traded on all three exchanges: Binance, Bybit, OKX.
This list is automatically generated from symbols.txt.
"""

ALLOWED_SYMBOLS = [
    "0GUSDT",
    "1INCHUSDT",
    "2ZUSDT",
    "AAVEUSDT",
    "ACEUSDT",
    "ACHUSDT",
    "ACTUSDT",
    "ADAUSDT",
    "AEROUSDT",
    "AEVOUSDT",
    "AGLDUSDT",
    "AIXBTUSDT",
    "ALGOUSDT",
    "ALLOUSDT",
    "ANIMEUSDT",
    "APEUSDT",
    "API3USDT",
    "APRUSDT",
    "APTUSDT",
    "ARBUSDT",
    "ARKMUSDT",
    "ARUSDT",
    "ASTERUSDT",
    "ATHUSDT",
    "ATOMUSDT",
    "ATUSDT",
    "AUCTIONUSDT",
    "AUSDT",
    "AVAXUSDT",
    "AVNTUSDT",
    "AXSUSDT",
    "BABYUSDT",
    "BANDUSDT",
    "BARDUSDT",
    "BATUSDT",
    "BCHUSDT",
    "BEATUSDT",
    "BERAUSDT",
    "BICOUSDT",
    "BIGTIMEUSDT",
    "BIOUSDT",
    "BLUAIUSDT",
    "BLURUSDT",
    "BNBUSDT",
    "BOMEUSDT",
    "BRETTUSDT",
    "BTCUSDT",
    "CATIUSDT",
    "CCUSDT",
    "CELOUSDT",
    "CETUSUSDT",
    "CFXUSDT",
    "CHZUSDT",
    "COAIUSDT",
    "COMPUSDT",
    "COOKIEUSDT",
    "CRVUSDT",
    "CVXUSDT",
    "DASHUSDT",
    "DEGENUSDT",
    "DOGEUSDT",
    "DOODUSDT",
    "DOTUSDT",
    "DYDXUSDT",
    "EDENUSDT",
    "EGLDUSDT",
    "EIGENUSDT",
    "ENAUSDT",
    "ENJUSDT",
    "ENSOUSDT",
    "ENSUSDT",
    "ETCUSDT",
    "ETHFIUSDT",
    "ETHUSDT",
    "FARTCOINUSDT",
    "FILUSDT",
    "FLOWUSDT",
    "FUSDT",
    "FXSUSDT",
    "GALAUSDT",
    "GASUSDT",
    "GIGGLEUSDT",
    "GLMUSDT",
    "GMTUSDT",
    "GMXUSDT",
    "GOATUSDT",
    "GPSUSDT",
    "GRASSUSDT",
    "GRTUSDT",
    "HBARUSDT",
    "HMSTRUSDT",
    "HOMEUSDT",
    "HUMAUSDT",
    "HUSDT",
    "HYPEUSDT",
    "ICPUSDT",
    "ICXUSDT",
    "IMXUSDT",
    "INITUSDT",
    "INJUSDT",
    "IOSTUSDT",
    "IOTAUSDT",
    "IPUSDT",
    "JCTUSDT",
    "JELLYJELLYUSDT",
    "JTOUSDT",
    "JUPUSDT",
    "KAITOUSDT",
    "KGENUSDT",
    "KITEUSDT",
    "KMNOUSDT",
    "KSMUSDT",
    "LABUSDT",
    "LAUSDT",
    "LDOUSDT",
    "LINEAUSDT",
    "LINKUSDT",
    "LPTUSDT",
    "LQTYUSDT",
    "LRCUSDT",
    "LTCUSDT",
    "MAGICUSDT",
    "MANAUSDT",
    "MASKUSDT",
    "MEMEUSDT",
    "MERLUSDT",
    "METISUSDT",
    "METUSDT",
    "MEUSDT",
    "MEWUSDT",
    "MINAUSDT",
    "MMTUSDT",
    "MONUSDT",
    "MOODENGUSDT",
    "MORPHOUSDT",
    "MOVEUSDT",
    "MUBARAKUSDT",
    "NEARUSDT",
    "NEOUSDT",
    "NEWTUSDT",
    "NMRUSDT",
    "NOTUSDT",
    "OLUSDT",
    "OMUSDT",
    "ONDOUSDT",
    "ONEUSDT",
    "ONTUSDT",
    "OPUSDT",
    "ORDERUSDT",
    "ORDIUSDT",
    "PARTIUSDT",
    "PENDLEUSDT",
    "PENGUUSDT",
    "PEOPLEUSDT",
    "PIEVERSEUSDT",
    "PLUMEUSDT",
    "PNUTUSDT",
    "POLUSDT",
    "POPCATUSDT",
    "PROMPTUSDT",
    "PROVEUSDT",
    "PYTHUSDT",
    "QTUMUSDT",
    "RECALLUSDT",
    "RENDERUSDT",
    "RESOLVUSDT",
    "RSRUSDT",
    "RVNUSDT",
    "SAHARAUSDT",
    "SANDUSDT",
    "SAPIENUSDT",
    "SEIUSDT",
    "SHELLUSDT",
    "SIGNUSDT",
    "SKYUSDT",
    "SNXUSDT",
    "SOLUSDT",
    "SOLVUSDT"
]


def load_allowed_symbols():
    """Load list of allowed symbols from file or return default list."""
    try:
        # Try to load from symbols.txt file (if exists and updated)
        from pathlib import Path
        symbols_file = Path(__file__).parent.parent / "symbols.txt"
        if symbols_file.exists():
            with open(symbols_file, 'r') as f:
                symbols = [line.strip() for line in f if line.strip()]
                if symbols:
                    return symbols
    except Exception:
        pass
    
    # Return default list from this file
    return ALLOWED_SYMBOLS


def is_symbol_allowed(symbol: str) -> bool:
    """Check if symbol is in the allowed list."""
    allowed = load_allowed_symbols()
    return symbol in allowed
