# Generated by Django 5.2.8 on 2025-12-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0006_screenersnapshot_change_1m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenersnapshot',
            name='change_15m',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='change_1d',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='change_1h',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='change_1m',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='change_2m',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='change_30m',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='change_3m',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='change_5m',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='change_8h',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='oi_change_15m',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='oi_change_1d',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='oi_change_1h',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='oi_change_1m',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='oi_change_2m',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='oi_change_30m',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='oi_change_3m',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='oi_change_5m',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='oi_change_8h',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='vdelta_15m',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='vdelta_1d',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='vdelta_1h',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='vdelta_1m',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='vdelta_2m',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='vdelta_30m',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='vdelta_3m',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='vdelta_5m',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='vdelta_8h',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='volume_15m',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='volume_1d',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='volume_1h',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='volume_1m',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='volume_2m',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='volume_30m',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='volume_3m',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='volume_5m',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='screenersnapshot',
            name='volume_8h',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
    ]
