# Generated by Django 5.2.8 on 2025-12-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0007_add_performance_indexes'),
        ('screener', '0007_alter_screenersnapshot_change_15m_and_more'),
    ]

    operations = [
    ]
