# Generated by Django 5.2.8 on 2025-12-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0008_merge_20251207_0710'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='screenersnapshot',
            name='screener_sn_symbol_ts_idx',
        ),
    ]
