# Generated by Django 5.2.8 on 2025-12-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0009_optimize_indexes'),
        ('screener', '0009_remove_screenersnapshot_screener_sn_symbol_ts_idx'),
    ]

    operations = [
    ]
