# Generated by Django 5.2.8 on 2025-12-08 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0010_merge_20251208_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy (Long liquidated)'), ('SELL', 'Sell (Short liquidated)')], help_text='BUY = long liquidated, SELL = short liquidated', max_length=4)),
                ('price', models.DecimalField(decimal_places=8, help_text='Цена ликвидации', max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Размер ликвидации (в базовой валюте, например BTC)', max_digits=20)),
                ('notional_value', models.DecimalField(decimal_places=8, default=0.0, help_text='Размер в USDT (quantity × price)', max_digits=20)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Время ликвидации')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='liquidation',
            name='symbol',
            field=models.ForeignKey(help_text='Символ (BTCUSDT, ETHUSDT, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='liquidations', to='screener.symbol'),
        ),
        migrations.AddIndex(
            model_name='liquidation',
            index=models.Index(fields=['symbol', '-timestamp'], name='liq_symbol_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidation',
            index=models.Index(fields=['-timestamp'], name='liq_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidation',
            index=models.Index(fields=['-notional_value'], name='liq_notional_idx'),
        ),
    ]
