# Generated by Django 5.2.8 on 2025-12-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0011_add_liquidation_model'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='screenersnapshot',
            name='idx_snapshot_symbol_ts',
        ),
        migrations.AddField(
            model_name='screenersnapshot',
            name='change_4h',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='screenersnapshot',
            name='oi_change_4h',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='screenersnapshot',
            name='ticks_1d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='screenersnapshot',
            name='ticks_4h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='screenersnapshot',
            name='ticks_8h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='screenersnapshot',
            name='vdelta_4h',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='screenersnapshot',
            name='volatility_1d',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='screenersnapshot',
            name='volatility_4h',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='screenersnapshot',
            name='volatility_8h',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='screenersnapshot',
            name='volume_4h',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
    ]
