name: LyxenTrading
options:
  bundleIdPrefix: io.lyxen
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  defaultConfig: Release

configs:
  Debug:
    settings:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
  Release:
    settings:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    ENABLE_BITCODE: false

targets:
  LyxenTrading:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Models
      - path: Services
      - path: ViewModels
      - path: Views
      - path: Extensions
      - path: Utils
      - path: Resources
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.lyxen.trading
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: NDGY75Y29A
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: true
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: Lyxen
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ENABLE_PREVIEWS: true
        INFOPLIST_OUTPUT_FORMAT: xml

schemes:
  LyxenTrading:
    build:
      targets:
        LyxenTrading: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
