package io.lyxen.trading.ui.screens.ai

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import io.lyxen.trading.data.api.LyxenApi
import io.lyxen.trading.data.models.AIChatRequest
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

data class AIUiState(
    val messages: List<ChatMessage> = emptyList(),
    val isLoading: Boolean = false,
    val error: String? = null
)

@HiltViewModel
class AIViewModel @Inject constructor(
    private val api: LyxenApi
) : ViewModel() {
    
    private val _uiState = MutableStateFlow(AIUiState())
    val uiState: StateFlow<AIUiState> = _uiState.asStateFlow()
    
    private var messageIdCounter = 0
    
    fun sendMessage(content: String) {
        viewModelScope.launch {
            // Add user message
            val userMessage = ChatMessage(
                id = messageIdCounter++,
                content = content,
                isUser = true
            )
            _uiState.value = _uiState.value.copy(
                messages = _uiState.value.messages + userMessage,
                isLoading = true
            )
            
            try {
                val response = api.sendAiMessage(AIChatRequest(message = content))
                if (response.isSuccessful) {
                    val aiResponse = response.body()?.response
                        ?: "I couldn't process your request. Please try again."
                    addAIMessage(aiResponse)
                } else {
                    addMockResponse(content)
                }
            } catch (e: Exception) {
                addMockResponse(content)
            }
        }
    }
    
    private fun addAIMessage(content: String) {
        val aiMessage = ChatMessage(
            id = messageIdCounter++,
            content = content,
            isUser = false
        )
        _uiState.value = _uiState.value.copy(
            messages = _uiState.value.messages + aiMessage,
            isLoading = false
        )
    }
    
    private fun addMockResponse(userQuery: String) {
        val response = when {
            userQuery.contains("btc", ignoreCase = true) || 
            userQuery.contains("bitcoin", ignoreCase = true) -> {
                """
                📊 **Bitcoin Analysis**
                
                Current Price: ~$97,500
                24h Change: +2.3%
                
                **Technical Analysis:**
                • RSI: 58 (Neutral)
                • MACD: Bullish crossover forming
                • Support: $95,000
                • Resistance: $100,000
                
                **Recommendation:** 
                Consider a cautious long position with stop loss at $95,000. The market shows bullish momentum but watch for resistance at the psychological $100k level.
                """.trimIndent()
            }
            userQuery.contains("signal", ignoreCase = true) -> {
                """
                📈 **Top Signals Today:**
                
                1. **SOLUSDT** - LONG
                   Entry: $242.50 | TP: $255 | SL: $235
                   Confidence: 82%
                   
                2. **ETHUSDT** - LONG  
                   Entry: $3,150 | TP: $3,300 | SL: $3,050
                   Confidence: 78%
                   
                3. **XRPUSDT** - LONG
                   Entry: $3.15 | TP: $3.30 | SL: $3.05
                   Confidence: 75%
                   
                💡 These signals are generated by our OI and Fibonacci strategies.
                """.trimIndent()
            }
            userQuery.contains("strategy", ignoreCase = true) ||
            userQuery.contains("tip", ignoreCase = true) -> {
                """
                💡 **Strategy Tips:**
                
                1. **Risk Management**
                   Never risk more than 1-2% per trade
                   
                2. **Use Multiple Timeframes**
                   Confirm signals on 1H and 4H charts
                   
                3. **Set Realistic Targets**
                   TP/SL ratio of at least 1.5:1
                   
                4. **Enable ATR Trailing**
                   Let winners run with dynamic stops
                   
                5. **Diversify Strategies**
                   Use OI for trends, Scalper for ranges
                   
                Would you like me to explain any strategy in detail?
                """.trimIndent()
            }
            userQuery.contains("market", ignoreCase = true) ||
            userQuery.contains("outlook", ignoreCase = true) -> {
                """
                🎯 **Market Outlook**
                
                **Overall Sentiment:** Bullish 📈
                
                **Key Levels to Watch:**
                • BTC: $100,000 resistance
                • ETH: $3,500 next target
                • Total Crypto Market Cap: $3.5T
                
                **Top Performers (24h):**
                • SOL: +5.2%
                • XRP: +4.8%
                • DOGE: +3.5%
                
                **Risk Factors:**
                • US economic data this week
                • High leverage in market
                
                Stay cautious and use proper risk management!
                """.trimIndent()
            }
            else -> {
                """
                Thanks for your question! I'm Lyxen AI Assistant.
                
                I can help you with:
                • 📊 Market analysis (ask about BTC, ETH, etc.)
                • 📈 Trading signals
                • 💡 Strategy recommendations
                • 🎯 Market outlook
                • ⚙️ Platform features
                
                What would you like to know more about?
                """.trimIndent()
            }
        }
        
        addAIMessage(response)
    }
    
    fun clearHistory() {
        _uiState.value = AIUiState()
        messageIdCounter = 0
    }
}
